apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
{{- range $k, $v:= .Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}

